name: Hello World
Author: Sid
description: "Greet Someone and Record the Time"
inputs:
  who_to_greet:
    description: "Who to greet"
    # required: true
    default: "World"
outputs:
  time:
    description: The time of Greeting
runs:
  using: "docker"
  # image: 'docker//node:18.16-alpine3.17'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who_to_greet }}
  env: 
    HELLO: WORLD  
  post-entrypoint: "/cleanup.sh"
  post-if: runner.os == 'linux'