name: Random JOke
Author: Sid
description: "Generate a random Joke"
inputs:
  slack_username:
    description: "Slack Username"
  upload_joke:
    description: "upload joke as an artifact"
  slack_webhook:
    description: "Slack Webhook"

outputs:
    joke: 
      description: The generated joke 
      value: ${{ steps.joke.outputs.random_joke }}
     
runs:
  using: composite
  steps: 
    - name: Generate a Joke
      shell: bash
      id: joke
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "random_joke<<EOF" >> "$GITHUB_OUTPUT"
        curl -s https://icanhazdadjoke.com/ >> "$GITHUB_OUTPUT"
        echo "" >> "$GITHUB_OUTPUT"
        echo "$EOF" >> "$GITHUB_OUTPUT"
    - name: GenearteJoke file
      shell: bash
      run: echo '${{ steps.joke.outputs.random_joke }}' > joke.txt
      if: inputs.upload_joke
    - name: upload the joke
      if: inputs.upload_joke
      uses: actions/artifacts@v3
      with:
        name: joke 
        path: joke.txt
    - name: send a slack message
      uses: docker://technosophos/slack-notify
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        SLACK_TITLE: Random Joke
        SLACK_MESSAGE: "${{ inputs.slack_usrname && format('{0}{1} {2}', '@', inputs.slack_username, steps.joke.outputs.random_joke) || steps.joke.outputs.random_joke }}"
        SLACK_COLOR: "#723fc4" 
