name: Docker
on:
  workflow_dispatch

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      env:
        API_URL: some-url.com
      ports:
        - 80
    steps:
      - name: Log Nodes & OS Versions
        run: |
          node -v
          cat /etc/os-release
      - name: Log env
        run: echo $API_URL
      - name: Set up Docker
        run: docker info
      - name: Run Docker Image with Entry Point
        run: docker run --entrypoint /usr/local/bin/code node:18.16-alpine3.17 -p 2+3
      - name: Log Node Version
        run: docker run node:18.16-alpine3.17 -v
