name: Reusable wf
on:
    workflow_call:
        outputs:
            date:
                description: "Date Value"
                value: ${{ jobs.generate-outputs.outputs.date }}

jobs:
    nested-workflow-call:
        uses: disisdsid/newwebapp/.github/workflows/reusable.yaml@main
        with: 
            name: 'Sid'
        secrets:
            access-token: ${{ secrets.ACCESS_TOKEN }}
    generate-outputs:
        runs-on: ubuntu-latest
        outputs:
            date: ${{ steps.date-step.outputs.date }}
        steps:
            - run: echo "date=$(date)" >> $GITHUB_OUTPUT
              id: date-step
