name: Stale Issues and PRs
on:
    schedule:
        - cron: "0 14 * * *"
        - cron: "0 * * * *"
        - cron: "0/1 * * * *"
jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v8
              with:
                stale-issue-message: "random message"
                days-before-stale: 1
                days-before-close: 5
                
                