name: Using Reusable Workflow
on:
    workflow_dispatch:
        inputs:
            name:
                description: "Input Description"
                type: string
                default: "Sid"
                required: true
jobs:
    caliing-a-reusable-wf:
        uses: disisdsid/newwebapp/.github/workflows/reusable.yaml@main
        with: 
            name: ${{ inputs.name }}
        secrets:
            access-token: ${{ secrets.ACCESS_TOKEN }}    
    calling-a-reusable-wf-in-the-same-repo:
        permissions:
            issues: read
        uses: ./.github/workflows/reusablewf.yaml
        secrets: inherit
    using-reusable-wf-output:
        runs-on: ubuntu-latest
        needs: calling-a-reusable-wf-in-the-same-repo
        steps:
            - run: echo ${{ needs.calling-a-reusable-wf-in-the-same-repo.outputs.date }}